### ISSUE TITLE
cant link gi on ubuntu 18.04

### ISSUE THREAD

**Issue by gprichter** [mcfletch/venv-hpl#1]
i have just the example case of gi on my machine, bound to 18.04 LTS because of delayed software for 20.04.
got a python3.6 as system default
and an app (https://github.com/GeraldJansen/hamster-tool.git) that requires py>=3.7 (due to `datetime.fromisoformat()`)

* installed a python3.8 but not fully initialized due to system python
* installed a virtual environment for that app `python3.8 -m venv --symlinks --system-site-packages py38-venv/`
* activated the venv
* running the app yields the 
```
ImportError: cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) (/usr/lib/python3/dist-packages/gi/__init__.py)
```
* pip installed the venvhpl
* `venv-hpl gi` returns
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) (/usr/lib/python3/dist-packages/gi/__init__.py)
Traceback (most recent call last):
  File "/home/<wherever>/hamster-tool/py38-venv/bin/venv-hpl", line 11, in <module>
    sys.exit(main())
  File "/home/<wherever>/hamster-tool/py38-venv/lib/python3.8/site-packages/venvhpl/venvhpl.py", line 61, in main
    sources.append((package, get_host_package_location(package)))
  File "/home/<wherever>/hamster-tool/py38-venv/lib/python3.8/site-packages/venvhpl/venvhpl.py", line 20, in get_host_package_location
    subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python3.8', '-c', 'import os, gi; print(os.path.abspath(os.path.dirname(gi.__file__)))']' returned non-zero exit status 1.
```
what am I missing?

-thanks!

**Comment by gprichter** [comment]
remark:
had the venvhpl installed on system level outside of the venv before
but also no luck with that, on `venv-hpl gi` in the venv I got
```
Traceback (most recent call last):
  File "/usr/bin/venv-hpl", line 11, in <module>
    load_entry_point('venvhpl==1.0.0', 'console_scripts', 'venv-hpl')()
  File "/usr/lib/python3/dist-packages/venvhpl/venvhpl.py", line 68, in main
    os.symlink(source, target)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/gi' -> '/usr/lib/python3.6/site-packages/gi'
```
